apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-deployment
  template:
    metadata:
      labels:
        app: go-deployment
    spec:
      containers:
        - name: go-deployment
          image: go-deployment:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080