apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-tokenize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-tokenize
  template:
    metadata:
      labels:
        app: go-tokenize
    spec:
      containers:
        - name: go-tokenize
          image: go-tokenize:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080