apiVersion: v1
kind: Service
metadata:
  name: go-tokenize
spec:
  selector:
    app: go-tokenize
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort