apiVersion: v1
kind: Service
metadata:
  name: go-deployment
spec:
  selector:
    app: go-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort